### ISSUE TITLE
Anleitung zu ungenau... Hab jetzt einen Virus :D

### ISSUE THREAD

**Issue by TheMatzy** [itsFabiDev/mc2dc#1]
Anleitung zu ungenau... Hab jetzt einen Virus :D

**Comment by itsFabiDev** [comment]
Abgelehnt

**Comment by TheMatzy** [comment]
<img width="400" alt="Flamy" src="https://user-images.githubusercontent.com/41703752/231424387-84ef67b7-1baa-4cf6-910b-1cb7a08a37cc.png">
